### ISSUE TITLE
Перестал работать перевод

### ISSUE THREAD

**Issue by kirillrybin** [podgorniy/alfred-translate#8]
Лог из дебаггера
 ```
[00:21:48.999] Translate[Script Filter] Queuing argument 'c'
[00:21:49.124] Translate[Script Filter] Queuing argument 'ca'
[00:21:49.285] Translate[Script Filter] Queuing argument 'cat'
[00:21:49.721] Translate[Script Filter] Script with argument '(null)' finished
[00:21:49.724] ERROR: Translate[Script Filter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "translate.py", line 133, in get_output
    responses = pool.map(process_response_as_json, requestsUrls)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>
 ```
Плагин переустанавливал.

 ```
~ python --version
Python 2.7.10
```

**Comment by kirillrybin** [comment]
Вновь заработало после обновления Alfred до версии 4.0.2
